# Production environment values
replicaCount: 3

image:
  repository: e2e-app
  tag: stable
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Production Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: e2e-app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: e2e-app-tls
      hosts:
        - e2e-app.example.com

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

config:
  appEnv: "production"
  logLevel: "info"
  apiVersion: "v1"
  serverPort: "8080"
  enableMetrics: "true"
  metricsPath: "/metrics"
  healthCheckPath: "/health"
  readinessCheckPath: "/ready"
  maxRequestsPerSecond: "200"
  timeoutSeconds: "30"

# Production secrets (replace with actual values)
secrets:
  dbHost: "prod-db.example.com"
  dbPort: "5432"
  dbName: "proddb"
  dbUser: "produser"
  # dbPassword: set this via CI/CD or command line
  # apiKey: set this via CI/CD or command line
  # apiSecret: set this via CI/CD or command line
  # jwtSecret: set this via CI/CD or command line