# Production environment values
replicaCount: 3

image:
  repository: e2e-app
  tag: stable
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Production Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: e2e-app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: e2e-app-tls
      hosts:
        - e2e-app.example.com

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

config:
  appEnv: "production"
  logLevel: "info"
  apiVersion: "v1"
  serverPort: "8080"
  enableMetrics: "true"
  metricsPath: "/metrics"
  healthCheckPath: "/health"
  readinessCheckPath: "/ready"
  maxRequestsPerSecond: "200"
  timeoutSeconds: "30"
  mockDB: "false"  # Ensure no mock DB in production

# Database configuration for production
database:
  enabled: true  # Enable PostgreSQL dependency in production
  type: postgres
  host: "{{ .Release.Name }}-postgresql"  # Uses the released PostgreSQL hostname
  port: 5432
  name: e2e_app_prod
  user: e2e_app
  existingSecret: "e2e-app-db-credentials"  # Reference existing secret for credentials

# Configure PostgreSQL for production
postgresql:
  enabled: true
  auth:
    username: e2e_app
    password: null  # Will be provided via external secrets management
    database: e2e_app_prod
    existingSecret: "e2e-app-db-credentials"
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  metrics:
    enabled: true  # Enable PostgreSQL metrics exporter
  
# Create a secret for database credentials (should be managed by external secrets in real prod)
secrets:
  create: true
  dbPasswordKey: "postgresql-password"