# Development environment values
replicaCount: 1

image:
  repository: e2e-app
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Development Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: dev.e2e-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

config:
  appEnv: "development"
  logLevel: "debug"
  apiVersion: "v1"
  serverPort: "8080"
  enableMetrics: "true"
  metricsPath: "/metrics"
  healthCheckPath: "/health"
  readinessCheckPath: "/ready"
  maxRequestsPerSecond: "50"
  timeoutSeconds: "30"
  mockDB: "false"  # Disable mock database for development

# Database configuration for development
database:
  enabled: true  # Enable PostgreSQL dependency in development
  type: postgres
  host: "{{ .Release.Name }}-postgresql"
  port: 5432
  name: e2e_app_dev
  user: postgres
  password: postgres
  existingSecret: ""

# Configure PostgreSQL for development
postgresql:
  enabled: true  # Enable PostgreSQL in development
  auth:
    username: postgres
    password: postgres
    database: e2e_app_dev
  primary:
    persistence:
      enabled: true
      size: 1Gi

# Development secrets (replace with actual values)
secrets:
  dbHost: "dev-db.example.com"
  dbPort: "5432"
  dbName: "devdb"
  dbUser: "devuser"
  # dbPassword: set this via CI/CD or command line
  # apiKey: set this via CI/CD or command line
  # apiSecret: set this via CI/CD or command line
  # jwtSecret: set this via CI/CD or command line