apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - e2e-profile-service.yaml
  - e2e-profile-deployment.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml

commonLabels:
  app: e2e-app
  managed-by: kustomize