apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to the base directory
resources:
- ../../base

# Namespace for all resources
namespace: e2e-tanerincode-prod

# Add environment-specific labels
commonLabels:
  environment: production

# Modify the base resources
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: e2e-app
    spec:
      replicas: 3
      template:
        spec:
          containers:
          - name: e2e-app
            resources:
              requests:
                cpu: "500m"
                memory: "512Mi"
              limits:
                cpu: "1000m"
                memory: "1Gi"
            env:
            - name: ENVIRONMENT
              value: "production"