apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "e2e-app.fullname" . }}
  labels:
    {{- include "e2e-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "e2e-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "e2e-app.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: APP_ENV
              value: {{ .Values.config.appEnv | quote }}
            - name: MOCK_DB
              value: {{ .Values.config.mockDB | quote }}
            - name: DB_HOST
              {{- if .Values.postgresql.enabled }}
              value: {{ include "e2e-app.fullname" . }}-postgresql
              {{- else }}
              value: {{ .Values.database.host | quote }}
              {{- end }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: DB_NAME
              {{- if .Values.postgresql.enabled }}
              value: {{ .Values.postgresql.auth.database | quote }}
              {{- else }}
              value: {{ .Values.database.name | quote }}
              {{- end }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  {{- if .Values.database.existingSecret }}
                  name: {{ .Values.database.existingSecret }}
                  {{- else }}
                  name: {{ include "e2e-app.fullname" . }}-db-credentials
                  {{- end }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.database.existingSecret }}
                  name: {{ .Values.database.existingSecret }}
                  {{- else }}
                  name: {{ include "e2e-app.fullname" . }}-db-credentials
                  {{- end }}
                  key: password
            - name: JWT_SECRET
              {{- if .Values.jwt.secret }}
              valueFrom:
                secretKeyRef:
                  {{- if .Values.database.existingSecret }}
                  name: {{ .Values.database.existingSecret }}
                  {{- else }}
                  name: {{ include "e2e-app.fullname" . }}-db-credentials
                  {{- end }}
                  key: jwt-secret
              {{- else }}
              value: {{ .Values.jwt.secret | quote }}
              {{- end }}
            - name: JWT_EXPIRATION
              value: {{ .Values.jwt.expiration | quote }}
            - name: REFRESH_EXPIRATION
              value: {{ .Values.jwt.refreshExpiration | quote }}
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: GRPC_PORT
              value: {{ .Values.service.grpcPort | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}