apiVersion: v1
kind: Service
metadata:
  name: {{ include "e2e-app.fullname" . }}
  labels:
    {{- include "e2e-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "e2e-app.selectorLabels" . | nindent 4 }}