apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to the base directory
resources:
- ../../base

# Namespace for all resources
namespace: e2e-tanerincode-dev

# Add environment-specific labels
commonLabels:
  environment: development

# Modify the base resources
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: e2e-app
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: e2e-app
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
            env:
            - name: ENVIRONMENT
              value: "development"