{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "e2e-profile.fullname" . }}-db-credentials
  labels:
    {{- include "e2e-profile.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  # Use provided credentials when PostgreSQL is enabled via dependency
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | default "postgres" | b64enc }}
  postgresql-password: {{ .Values.postgresql.auth.password | default "postgres" | b64enc }}
  {{- else }}
  # Use regular database credentials when using external database
  username: {{ .Values.database.user | b64enc }}
  password: {{ .Values.database.password | default "postgres" | b64enc }}
  {{- end }}
{{- end }}